## Intro to NumPy

In [1]:
lis = [1,2,3,4,5,6]

In [4]:
import numpy as np

In [3]:
np.array(lis)

array([1, 2, 3, 4, 5, 6])

In [6]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(2,10,23)

array([ 2.        ,  2.36363636,  2.72727273,  3.09090909,  3.45454545,
        3.81818182,  4.18181818,  4.54545455,  4.90909091,  5.27272727,
        5.63636364,  6.        ,  6.36363636,  6.72727273,  7.09090909,
        7.45454545,  7.81818182,  8.18181818,  8.54545455,  8.90909091,
        9.27272727,  9.63636364, 10.        ])

In [17]:
np.random.rand(3)

array([0.43269486, 0.762799  , 0.11732377])

In [18]:
np.random.randn(3)

array([ 0.91283107, -2.53643825,  1.80328753])

randn gives points from a standard normal distribution.

In [20]:
np.random.randn(3,3)

array([[ 0.53849638,  0.78381848,  0.3898923 ],
       [ 1.04173121,  1.37744737,  1.40668113],
       [-0.77689439, -0.2047282 ,  1.04709672]])

In [22]:
np.random.randint(10,100,3)

array([33, 81, 34])

In [24]:
randarr = np.random.randint(10,100,25)

In [25]:
randarr

array([73, 77, 21, 37, 31, 77, 94, 45, 18, 88, 56, 49, 65, 74, 59, 35, 25,
       26, 90, 31, 36, 36, 51, 26, 34])

In [29]:
np.reshape(randarr,(5,5))

array([[73, 77, 21, 37, 31],
       [77, 94, 45, 18, 88],
       [56, 49, 65, 74, 59],
       [35, 25, 26, 90, 31],
       [36, 36, 51, 26, 34]])

In new dimension, Row * Col must be == to len(np_array)

In [31]:
randarr.max()

94

In [32]:
randarr.argmax()

6

returns the index of max of array

In [34]:
randarr.min()

18

In [35]:
randarr.argmin()

8

In [36]:
randarr.shape

(25,)

In [39]:
ran = randarr.reshape(5,5)

In [40]:
ran

array([[73, 77, 21, 37, 31],
       [77, 94, 45, 18, 88],
       [56, 49, 65, 74, 59],
       [35, 25, 26, 90, 31],
       [36, 36, 51, 26, 34]])

In [41]:
ran.shape

(5, 5)

In [42]:
ran.dtype

dtype('int32')

### Indexing and Selection in Numpy

Very much similar to usual lists

In [81]:
liss = np.array(list(range(0,24,2)))
liss

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [82]:
liss[7]

14

In [83]:
liss[:]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [84]:
liss[5:]

array([10, 12, 14, 16, 18, 20, 22])

In [85]:
liss[-1:-12:-1]

array([22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [86]:
liss[-1:0:-1]

array([22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Unlike normal lists, np arrays can broadcast values.

In [88]:
liss[1:5] = 5
liss

array([ 0,  5,  5,  5,  5, 10, 12, 14, 16, 18, 20, 22])

In [89]:
lis = liss[1:5]

In [90]:
lis[:] = 0

In [91]:
lis

array([0, 0, 0, 0])

In [92]:
liss

array([ 0,  0,  0,  0,  0, 10, 12, 14, 16, 18, 20, 22])

As observed, slicing does not copy the np array unlike lists as changes are visible to original array.

In [93]:
lis[0] = 99

In [94]:
lis

array([99,  0,  0,  0])

In [95]:
liss

array([ 0, 99,  0,  0,  0, 10, 12, 14, 16, 18, 20, 22])

lis was image of liss from index 1:5 so the lis[0] assignment in lis was refected at 1 index of liss.

In [99]:
lis = liss.copy()
lis

array([ 0, 99,  0,  0,  0, 10, 12, 14, 16, 18, 20, 22])

In [101]:
lis[:4] = 32
lis

array([32, 32, 32, 32,  0, 10, 12, 14, 16, 18, 20, 22])

In [102]:
liss

array([ 0, 99,  0,  0,  0, 10, 12, 14, 16, 18, 20, 22])

In [116]:
alist = np.array([list(range(1,26))])
alist = alist.reshape(5,5)
alist

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [113]:
alist[1][1]

7

In [118]:
alist[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [123]:
blist = np.array(list(range(2,30)))
blist

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [127]:
temp = blist > 9
temp

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [128]:
blist[temp]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

More direct approach to suffice above two steps would be:

In [129]:
blist[blist > 9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

#### Operations in NumPy

In [10]:
alist = np.array(list(range(0,24,2)))
alist

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [11]:
alist + alist

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])

In [12]:
alist - alist

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
alist * alist

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484])

In [14]:
alist / alist

C:\Users\prash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Notice that the division by zero in the first element is treated as a warning in NumPy and 'nan' type is provided in the output.

In [18]:
alist ** 3

array([    0,     8,    64,   216,   512,  1000,  1728,  2744,  4096,
        5832,  8000, 10648], dtype=int32)

In [19]:
alist - 100

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
        -78])

In [23]:
np.sqrt(alist)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576])

In [24]:
np.exp(alist)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09])

In [25]:
np.max(alist)

22

In [26]:
alist.max()

22

In [27]:
np.sin(alist)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131])

In [28]:
np.log(alist)

C:\Users\prash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227, 3.09104245])

Notice the -inf as the output for log 0.

https://docs.scipy.org/doc/numpy/reference/ufuncs.html